In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('df_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()
# I used the median as a cutoff line so that the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression).
# 3 Hours

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
# created targets for the Regression which must be categories so I can tell whether an employee is 'being absent too much' or not
# If the employee has been absent for 4 hours or more (more than 3 hours), then they will be assigned the value '1', that is the equivalent of taking half a day off
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
# Created a Series in the original data frame that will contain the targets for the regression

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
targets.sum() / targets.shape[0]
# Checked if the dataset is balanced.

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)
# I dropped the unnecessary variables after exploring the weights.
data_with_targets is data_preprocessed
# I checked whether I created a checkpoint

False

In [10]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
data_with_targets.shape

(700, 12)

In [12]:
data_with_targets.iloc[:,:-1]
# I excluded 'Excessive Absenteeism' because that column contains my targets.

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [13]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
# Created a checkpoint variable that will contain the inputs (everything without the targets)

## Standardizing the data

In [14]:
from sklearn.preprocessing import StandardScaler
# I decided to use the StandardScaler module because it has much more capabilities than the straightforward 'preprocessing' method
absenteeism_scaler = StandardScaler()
# Here I defined scaler as an object.

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
# These are the libraries needed to create the Custom Scaler.
# Created the CustomScaler class below.

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # Here I declared what I want a CustomScaler object to do.
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        # Used Keywords Arguments here
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        
    
    # The fit method, which, again based on StandardScaler.
    
    def fit(self, X, y=None):
        self.scaler = StandardScaler(copy=self.copy, with_mean=self.with_mean, with_std=self.with_std)
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    
    # The transform method which does the actual scaling.

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        # This records the initial order of the columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        # This scales all chosen features when creating the instance of the class
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        # This declares a variable containing all information that was not scaled
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
        # This returns a data frame which contains all scaled features and all 'not scaled' features

In [16]:
unscaled_inputs.columns.values
# Here I checked the number of columns I got

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
# Here I created the columns to scale, and excluded the columns to omit, and used list comprehension to iterate over the list

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)
# Here I decared a CustomScaler object that specifies the columns I want to scale.

In [20]:
absenteeism_scaler.fit(unscaled_inputs)
# Here I fit the data to find the internal parameters of a model that will be used to transform the data.

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs
# Transformed data.

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [23]:
scaled_inputs.shape
# I checked the shape of the inputs

(700, 11)

## Split the data into train & test and shuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 508         1         0         0         0     1.039256   
 410         0         0         1         0    -0.959313   
 231         1         0         0         0    -0.102784   
 533         0         0         0         1     1.324766   
 236         0         0         1         0     0.182726   
 ..        ...       ...       ...       ...          ...   
 305         0         0         0         1     1.039256   
 23          0         0         0         1     0.468236   
 677         1         0         0         0    -0.388293   
 57          0         0         0         1     0.753746   
 284         0         0         0         1     0.753746   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 508                0.190942 -0.692937        -0.408580          1 -0.919030   
 410                0.568211 -0.065439        -0.878984          0  2.679969   
 231               -1.5746

In [26]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)
# I declared 4 variables for the split

In [27]:
print (x_train.shape, y_train.shape)
# Checked the shape of the train inputs and targets

(560, 11) (560,)


In [28]:
print (x_test.shape, y_test.shape)
# Checked the shape of the test inputs and targets

(140, 11) (140,)


## Logistic regression with sklearn

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
# The metrics module includes the important metrics that may be useful.

### Training the model

In [30]:
reg = LogisticRegression()

In [31]:
reg.fit(x_train,y_train)

LogisticRegression()

In [32]:
reg.score(x_train,y_train)

0.7732142857142857

### Manually check the accuracy

In [33]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum((model_outputs==y_train))
# This is the number of instances that the trained model predicted correctly.

433

In [36]:
model_outputs.shape[0]

560

In [37]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]
# Accuracy

0.7732142857142857

### Finding the intercept and coefficients

In [38]:
reg.intercept_
# Bias of the model

array([-1.6474549])

In [39]:
reg.coef_
# Weights of the model

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [40]:
unscaled_inputs.columns.values
# To check the names of the columns

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table
# I used the coeffcients in this table in Tableau.

Feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4              Month Value     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [43]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table
# I moved the intercept to the top of the summary table and added it at index 0, then sorted the dataframe by index.

Feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

In [44]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
# Created the Odds Ratio for each feature.
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5              Month Value     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [45]:
summary_table.sort_values('Odds_ratio', ascending=False)
# Sorted the table by the Odds Ratio of each feature, in descending order.

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

## Testing the model

In [46]:
reg.score(x_test,y_test)

0.75

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba
# These are the predicted probabilities of each class. 
# The first column shows the probability of a particular observation to be 0, while the second one - to be 1

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [48]:
predicted_proba.shape

(140, 2)

In [49]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

## Save the model

In [50]:
import pickle

In [51]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)
# Here I pickled the model file.

In [52]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)
# Here I pickled the scaler file.

In [53]:
from absenteeism_module import *
model = absenteeism_model ('model', 'scaler')
model.load_and_clean_data('Absenteeism_new_data.csv')
model.predicted_outputs()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0          0       0.0         0         1            6   
1          1       0.0         0         0            6   
2          0       0.0         0         1            6   
3          0       0.0         0         1            6   
4          1       0.0         0         0            6   
5          1       0.0         0         0            6   
6          1       0.0         0         0            6   
7          0       0.0         0         1            6   
8          0       0.0         0         1            6   
9          1       0.0         0         0            6   
10         0       0.0         0         1            6   
11         0       0.0         1         0            6   
12         0       0.0         1         0            6   
13         0       0.0         0         1            6   
14         0       0.0         0         0            6   
15         0       0.0         0         0            6   
16         0       0.0         1         0            6   
17         1       0.0         0         0            6   
18         0       0.0         0         1            6   
19         1       0.0         0         0            7   
20         0       0.0         0         1            7   
21         0       0.0         0         1            7   
22         1       0.0         0         0            7   
23         1       0.0         0         0            7   
24         0       0.0         0         1            7   
25         0       0.0         0         1            7   
26         0       0.0         1         0            7   
27         1       0.0         0         0            7   
28         0       0.0         0         1            7   
29         1       0.0         0         0            7   
30         0       0.0         0         1            7   
31         0       0.0         0         1            7   
32         0       0.0         0         1            7   
33         0       0.0         0         1            7   
34         1       0.0         0         0            7   
35         1       0.0         0         0            7   
36         1       0.0         0         0            7   
37         0       0.0         0         0            7   
38         0       0.0         0         0            7   
39         0       0.0         0         0            7   

    Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                      179   30               19          1         0     0   
1                      361   28               27          0         1     4   
2                      155   34               25          0         2     0   
3                      179   40               22          1         2     0   
4                      155   34               25          0         2     0   
5                      225   28               24          0         1     2   
6                      118   46               25          0         2     0   
7                      179   30               19          1         0     0   
8                      118   37               28          0         0     0   
9                      118   37               28          0         0     0   
10                     378   36               21          0         2     4   
11                     118   50               31          0         1     0   
12                     233   31               21          1         1     8   
13                     179   30               19          1         0     0   
14                     235   48               33          0         1     5   
15                     268   33               25          1         0     0   
16                     118   50               31          0         1     0   
17                     179   30               19          1         0     0   
18                     291   40               25          0         1     1   
19  